[package]
name = "therepo"
authors = ["kenf1"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.22", features = ["blocking"] }
scraper = "0.18.1"
tokio = { version = "1.34.0", features = ["full"] }
